name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Swift test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: SwiftyLab/setup-swift@v1
      - name: Show Swift version
        run: swift --version
      - name: Build & test
        run: swift test -v
